t = (1, 1, 2, 3)
#print(t[0])
#t1 = ()
#print(t1)
#t2 = (1,)
#print(t2)
print(t.count(1))
print(t.index(3))
f1 = input("Enter fruit 1:")
f2 = input("Enter fruit 2:")
f3 = input("Enter fruit 3:")
f4 = input("Enter fruit 4:")
f5 = input("Enter fruit 5:")
f6 = input("Enter fruit 6:")
f7 = input("Enter fruit 7:")
myFruitList = [f1, f2, f3, f4, f5, f6, f7]
print(myFruitList)
t = [7,0,8,0,0,9]
print(t.count(0))